#!/usr/bin/env python3
"""Re-apply the bare-name @font-face patch to the design-sync reference storybook.

The reference (.design-sync/sb-reference/) is gitignored + regenerated by every
`npx storybook build`, which DROPS this patch. Run this after each reference
rebuild so the compare oracle renders "Inter Tight" / "JetBrains Mono" (the bare
family names the DS's styles.css resolves to) with the real woff2 on BOTH sides —
matching the bundle, which ships these via cfg.extraFonts. Idempotent.

  python3 .design-sync/patch-reference-fonts.py
"""
import os, sys, glob

REF = os.path.join(os.path.dirname(__file__), "sb-reference")
f = os.path.join(REF, "iframe.html")
MARKER = "/* ds-sync bare-name font alias */"


def woff2(prefix):
    # The fontsource latin woff2 land in assets/ with a content hash suffix.
    hits = sorted(glob.glob(os.path.join(REF, "assets", prefix + "*.woff2")))
    hits = [h for h in hits if "italic" not in h]
    if not hits:
        sys.exit(f"missing reference woff2 for {prefix}")
    return "./assets/" + os.path.basename(hits[0])


def main():
    html = open(f).read()
    if MARKER in html:
        print("already patched")
        return
    faces = []
    for fam, prefix in [
        ("Inter Tight", "inter-tight-latin-wght-normal"),
        ("Inter Tight", "inter-tight-latin-ext-wght-normal"),
        ("JetBrains Mono", "jetbrains-mono-latin-wght-normal"),
        ("JetBrains Mono", "jetbrains-mono-latin-ext-wght-normal"),
    ]:
        faces.append(
            f'      @font-face {{ font-family:"{fam}"; font-style:normal; '
            f'font-weight:100 900; font-display:swap; '
            f'src:url("{woff2(prefix)}") format("woff2-variations"); }}'
        )
    block = f"    <style>{MARKER}\n" + "\n".join(faces) + "\n    </style>\n"
    anchor = '    <meta name="viewport" content="width=device-width, initial-scale=1" />\n'
    if anchor not in html:
        sys.exit("anchor not found in iframe.html")
    open(f, "w").write(html.replace(anchor, anchor + block, 1))
    print("patched iframe.html with bare-name @font-face")


if __name__ == "__main__":
    main()
